version: '2'
services:
  app:
    image: flipjms/nginx-php7.1
    volumes:
     - ./public_html:/var/www/html/public
     - ./developer:/var/www/html/developer
    networks:
     - net
    ports:
     - "80:80"
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "wp_test"
      MYSQL_USER: "wp_user"
      MYSQL_PASSWORD: "secret"
    volumes:
     - mysql_data:/var/lib/mysql
    networks:
     - net
networks:
  net:
    driver: "bridge"
volumes:
  mysql_data:
    driver: "local"
